In [1]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
import scipy.stats as stats
import seaborn as sns
import os
import os.path
from os.path import dirname, join as pjoin
import sys
import argparse
import scipy.io as io
import glob
import sys

In [2]:
baseDir = '/Users/Eichenbaum/HWNI/Experiments/HRL_Geometry'
scriptDir = baseDir + '/scripts/analysis/extract_task_timing_data'
behavDir_base = baseDir + '/data/behav'

In [3]:
subs = ['001', '002', '003', '004', '005', '006', '007', '008']

In [4]:
nTrialsTotal = np.ones(len(subs)) * 0
nBlocksTotal = np.ones(len(subs)) * 0
nNoResp = np.ones(len(subs)) * 0
nErrors = np.ones(len(subs)) * 0
nSOT = np.ones(len(subs)) * 0
nCOT = np.ones(len(subs)) * 0


for idx, sub in enumerate(subs):
    
    nBlocks = np.shape(glob.glob(behavDir_base+'/%s/%s_HRL_Geo_Run*' %(sub, sub)))[0]
    nTrialsTotal[idx] = np.multiply(nBlocks, 32)
    nBlocksTotal[idx] = nBlocks
    
    for block in range(nBlocks):
        
        if sub in ['001', '002', '003']:
            fname = glob.glob(behavDir_base+'/%s/%s_HRL_Geo_Run_%s.csv' %(sub, sub,block+1))
        else:
            fname = glob.glob(behavDir_base+'/%s/%s_HRL_Geo_Run_%s_' %(sub, sub,block+1) + '*')
            
        raw_data_arr = pd.read_csv(fname[0]).get_values()
        
        tOut_arr = np.asarray(raw_data_arr[:,22])
        
        if np.shape(np.where(tOut_arr == 'False'))[1] > 0:
            columnFilter_StimResp_Inc = list(np.where(np.logical_or(tOut_arr == '1', tOut_arr == 'False'))).pop()
            
            columnFilter_NoResp = list(np.where(np.logical_or(tOut_arr == '1', tOut_arr == '-1'))).pop()
            filtData_noResp = pd.read_csv(fname[0], skiprows = columnFilter_NoResp + 1)
            nNoResp[idx] += np.shape(filtData_noResp)[0]
        
        else: 
            columnFilter_StimResp_Inc = list(np.where(tOut_arr == 1)).pop()
            
            nNoResp[idx] += 0
        
        filtData = pd.read_csv(fname[0], skiprows = columnFilter_StimResp_Inc + 1)
        nErrors[idx] += np.shape(filtData)[0]
        
        ## Errors during "Shape on Top" ##
        nSOT[idx] += np.shape(np.where(filtData['Rule'] == 'Shape-on-Top'))[1]
        
        ## Errors during "Color on Top" ##
        nCOT[idx] += np.shape(np.where(filtData['Rule'] == 'Color-on-Top'))[1]

In [5]:
print('Number of Total Trials\n', nTrialsTotal)
print('\nNumber of Blocks\n', nBlocksTotal)
print('\nNumber of No-Response trials\n', nNoResp)
print('\nNumber of Errors\n', nErrors)
print('\nErrors in Shape on Top\n', nSOT)
print('\nErrors in Color on Top\n', nCOT)

Number of Total Trials
 [320. 512. 448. 448. 576. 544. 512. 576.]

Number of Blocks
 [10. 16. 14. 14. 18. 17. 16. 18.]

Number of No-Response trials
 [ 5. 40. 22. 27.  2. 27. 41.  4.]

Number of Errors
 [21. 73. 42. 86. 37. 15. 46. 26.]

Errors in Shape on Top
 [11. 27. 24. 40. 19.  8. 29. 20.]

Errors in Color on Top
 [10. 46. 18. 46. 18.  7. 17.  6.]
